Ed gen wave
dudublad/ECE496 pull request #41
Opened 2022-02-26 23:21 UTC by dudublad

2022-02-26 23:21 UTC, dudublad commented on QT/sinewavedisplay.cpp
> +    waveTypeSelector = new QComboBox(this);
@Maxarreaga This is the stuff to change the wave type

2022-02-26 23:22 UTC, dudublad commented on backend/audiofile.cpp
> +    //TODO: FIX SAMPLING RATE FOR SOUND
@luckuisha

2022-03-05 20:41 UTC, luckuisha requested changes

2022-03-05 20:41 UTC, luckuisha commented on QT/main.cpp
> +    stk::Stk::setSampleRate(140000.0);
132300.0

2022-03-05 20:41 UTC, luckuisha commented on backend/wave.h
>  #endif
use qt pi

2022-03-06 19:12 UTC, Maxarreaga approved these changes
LGTM, we'll merge the front end this week

2022-03-08 03:50 UTC, luckuisha approved these changes

2022-03-08 03:51 UTC, merged