Implements Scrollview, Volume, Effect Panel and Effect Dialog
dudublad/ECE496 pull request #42
Opened 2022-03-09 02:19 UTC by Maxarreaga

2022-03-09 19:12 UTC, luckuisha commented on QT/sounddisplay.cpp
> +void SoundDisplay::volumeChanged(int changedVolume)
change int to float

2022-03-09 20:19 UTC, luckuisha requested changes, later dismissed
fix the play button before merge. else looks good

2022-03-12 20:36 UTC, dudublad submitted a review, later dismissed

2022-03-12 20:36 UTC, dudublad commented on QT/frequencydomaindisplay.cpp
> +
Why is this here?

2022-03-12 20:36 UTC, dudublad commented on QT/recordedsounddisplay.cpp
> +    idLabel = new QLabel(this);
I don't think we should keep this

2022-03-12 20:36 UTC, dudublad commented on QT/sounddisplay.cpp
> +    volumeSlider->setMaximum(100);
volume slider is not working for recorded input

2022-03-12 20:36 UTC, dudublad commented on QT/sounddisplay.cpp
> -    delete domainLayout;
Where does this get done? It needs to be deleted especially cus now we are adding and removing instances of SoundDisplay

2022-03-12 20:36 UTC, dudublad commented on QT/sounddisplay.cpp
> +    this->setVisible(false);
When does the actual instance of the class get deleted?

2022-03-12 20:36 UTC, dudublad commented on QT/inputscrollview.cpp
> +            inputSubScrollLayout->removeWidget(widget);
delete WaveDisplay?
Update the vector?

2022-03-12 20:36 UTC, dudublad commented on QT/wavedisplay.cpp
This class needs a destructor

2022-03-12 20:36 UTC, dudublad commented on QT/wavedisplay.cpp
> +void WaveDisplay::onSpinBoxChanged(double value)
I think we need to limit the rate at which things get updated to prevent the program from crashing. I'll look into it

2022-04-05 01:23 UTC, luckuisha commented on QT/sounddisplay.cpp
> +    volumeSlider->setMaximum(100);
figure this out later

2022-04-05 01:35 UTC, merged